#!/bin/bash
############################## !!! IMPORTANTE !!! #######################################
#                                                                                       #
# Nome Script : installer_cam                                                           #
# Versione: Local Repository                                                            #
#                                                                                       #
#                                                                                       #
# Da terminale:                                                                         #
# date il comando sudo chmod 755 installer_cam                                          #
# avviate lo script con il comando: sudo sh ./installer_cam                             #
#                                                                                       #
#########################################################################################

#############################################################################################################################  
#############################################################################################################################
###                                                                                                                       ###
## 
                                                                                                                       
SRC='/usr/local/src';
Remind2='è già installata'
Remind3='è già installato'

#############################################################################################################################  
#############################################################################################################################

while :
    do 
    dialog --title "   ** Installazione cam **   " --infobox "

   ----------------------------------------------   
	[a]  Caricamento dal cloud	
       
	[b]  Oscam	
	[c]  NCam 
	[d]  CCcam (server)
  
	[z]  Esci  
   ---------------------------------------------- " 0 0

    echo -n "        Scegli  [a-z]:      "
    read yourch
    case $yourch in

                                          ##################################################
                                          #          Caricamento dal cloud                 #
                                          ##################################################

a)
cd /home/`logname`/; mkdir -p sifinstallrepo;
cd sifinstallrepo;

if [ -s /home/`logname`/sifinstallrepo/icone.tar.gz ]; then
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File Presente ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
else
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File non Presente ... Eseguo il Download ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
    wget https://www.dropbox.com/s/5uvx468b4b87auy/icone.tar.gz;
  fi

if [ -s /home/`logname`/sifinstallrepo/oscam64.tar.gz ]; then
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File Presente ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
else
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File non Presente ... Eseguo il Download ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
    wget https://www.dropbox.com/s/lvs3eb7q64ericc/oscam64.tar.gz;
  fi

if [ -s /home/`logname`/sifinstallrepo/oscam.tar.gz ]; then
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File Presente ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
else
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File non Presente ... Eseguo il Download ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
    wget https://www.dropbox.com/s/56oomdr58os7msa/oscam.tar.gz;
fi

if [ -s /home/`logname`/sifinstallrepo/ncam64.tar.gz ]; then
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File Presente ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
else
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File non Presente ... Eseguo il Download ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
    wget https://www.dropbox.com/s/958zgoqyf4gqqwf/ncam64.tar.gz;
  fi

if [ -s /home/`logname`/sifinstallrepo/ncam.tar.gz ]; then
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File Presente ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
else
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File non Presente ... Eseguo il Download ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
    wget https://www.dropbox.com/s/a12jwqkbycdfcoj/ncam.tar.gz;
fi

if [ -s /home/`logname`/sifinstallrepo/CCcam64.tar.gz ]; then
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File Presente ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
else
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File non Presente ... Eseguo il Download ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
    wget https://www.dropbox.com/s/rq8gu43w2llh59l/CCcam64.tar.gz;
  fi

if [ -s /home/`logname`/sifinstallrepo/CCcam.tar.gz ]; then
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File Presente ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
else
  echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░¦¦¦¦¦¦:::: ..... File non Presente ... Eseguo il Download ..... ::::¦¦¦¦¦¦░░░░░░░░░░░░░░░░░░░░░░░░░░░░░";
    wget https://www.dropbox.com/s/l45kq9onhl61tdm/CCcam.tar.gz;
fi


chmod -R 777 *;

cp -rf /home/`logname`/sifinstallrepo/icone.tar.gz /usr/local/src/; cd $SRC;
tar -zxvf icone.tar.gz; rm -r icone.tar.gz;

    echo "                    Premere il tasto [Invio] per continuare. . .               "; read enterKey;;


#############################################################################################################################  
#############################################################################################################################
###                                                                                                                       ###
##                                                                                                                         ##

                                          ##################################################
                                          #                   Oscam                        #
                                          ##################################################

b)                                          
cd /usr/local; mkdir -p etc;                                          
if [ -f /usr/local/etc/oscam.check ];
  then  echo "Oscam $Remind3"
else
echo "oscam ALL=(ALL) ALL" >> /etc/sudoers; 
apt-get install libssl0.9.8 libcrypto++-dev; rm -r /etc/init.d/oscam; touch /etc/init.d/oscam; 

echo '
#!/bin/sh
#
# To be copied to: /etc/init.d
# And type:
### BEGIN INIT INFO
# Provides:          Oscam
# Required-Start:   
# Required-Stop:     
# Default-Start:     0 1 2 3 4 5 6
# Default-Stop:     
# Description:       Start, Stop or Restart Oscam
### END INIT INFO

# Shell functions sourced from /etc/rc.status:
set -e

# Reset status of this service
# rc_reset
#
echo "Vdr init.d script using: $1" >> /var/log/oscam.log &
case "$1" in
    start)
        echo -n "Avvio Oscam "
       /usr/local/bin/oscam >> /var/log/oscam.log &
        # Remember status and be verbose
        ;;
    stop)
        echo -n "Chiusura di Oscam "
       killall -9 oscam
        # Remember status and be verbose
        ;;
    restart)
        echo -n "Riavvio di Oscam "
        $0 stop
        $0 start

        # Remember status and be quiet
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
' >> /etc/init.d/oscam; chmod 755 /etc/init.d/oscam; echo "%`logname` ALL=NOPASSWD: /etc/init.d/oscam" >> /etc/sudoers; 
cd $SRC; mkdir -p oscam; cd oscam; cp -r /home/`logname`/sifinstallrepo/oscam.tar.gz /$SRC/oscam; tar -zxvf oscam.tar.gz; rm -rf oscam.tar.gz;
cp -r * /usr/local/etc/;
fi
   
if uname -m  | grep "x86_64"; then
    echo "64bit detected"; cp -r /home/`logname`/sifinstallrepo/oscam64.tar.gz /usr/local/bin/; cd /usr/local/bin; tar -zxvf oscam64.tar.gz; rm -rf oscam64.tar.gz;
    else echo "32bit detected"
        cp -r /home/`logname`/sifinstallrepo/oscam32.tar.gz /usr/local/bin/; cd /usr/local/bin; tar -zxvf oscam32.tar.gz; rm -rf oscam32.tar.gz;
fi
chmod 777 oscam;

rm -rf /home/`logname`/Scrivania/Oscam.desktop; rm -rf /usr/share/applications/Oscam.desktop;
touch /home/`logname`/Scrivania/Oscam.desktop; echo "[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Application
Name=Oscam
Description=avvio di Oscam
Icon=/usr/local/src/icone/Oscam.png
Exec=/usr/local/bin/start-oscam.sh
" >> /home/`logname`/Scrivania/Oscam.desktop; sudo chmod 777 /home/`logname`/Scrivania/Oscam.desktop; cp /home/`logname`/Scrivania/Oscam.desktop /usr/share/applications/Oscam.desktop;
rm -rf /usr/local/bin/start-oscam.sh; touch /usr/local/bin/start-oscam.sh; echo '#!/bin/sh 
sleep 10
sudo /etc/init.d/oscam start > /dev/null 2>&1
' >> /usr/local/bin/start-oscam.sh; chmod a+x /usr/local/bin/start-oscam.sh;

rm -rf /home/`logname`/Scrivania/KillOscam.desktop; rm -rf /usr/share/applications/KillOscam.desktop;
touch /home/`logname`/Scrivania/KillOscam.desktop; 
chmod 777 /home/`logname`/Scrivania/KillOscam.desktop;
echo "[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Application
Name=KillOscam
Description=Killa Oscam
Icon=/usr/local/src/icone/killoscam.png
Exec=/usr/local/bin/KillOscam.sh
" >> /home/`logname`/Scrivania/KillOscam.desktop; sudo chmod 777 /home/`logname`/Scrivania/KillOscam.desktop; cp /home/`logname`/Scrivania/KillOscam.desktop /usr/share/applications/KillOscam.desktop;
rm -rf /usr/local/bin/KillOscam.sh;
touch /usr/local/bin/KillOscam.sh
echo '#!/bin/sh

sudo /etc/init.d/oscam stop > /dev/null 2>&1
' >> /usr/local/bin/KillOscam.sh;
chmod a+x /usr/local/bin/KillOscam.sh;

    echo "                    Premere il tasto [Invio] per continuare. . .               "; read enterKey;;


#############################################################################################################################  
#############################################################################################################################
###                                                                                                                       ###
##                                                                                                                         ##

                                          ##################################################
                                          #                   NCam                         #
                                          ##################################################
                                          
c)
cd /var;  mkdir -p tuxbox; cd /var/tuxbox; mkdir -p config;                                    
if [ -f /var/tuxbox/config/ncam.check ];
  then  echo "NCam $Remind3"
else
echo "ncam ALL=(ALL) ALL" >> /etc/sudoers; 
apt-get install -y libssl-dev libcrypto++-dev; 

rm -r /etc/init.d/ncam; touch /etc/init.d/ncam; 
echo '
#!/bin/sh
#
# To be copied to: /etc/init.d
# And type:
### BEGIN INIT INFO
# Provides:          NCam
# Required-Start:   
# Required-Stop:     
# Default-Start:     0 1 2 3 4 5 6
# Default-Stop:     
# Description:       Start, Stop or Restart NCam
### END INIT INFO

# Shell functions sourced from /etc/rc.status:
set -e

# Reset status of this service
# rc_reset
#
echo "Ncam init.d script using: $1" >> /var/log/ncam.log &
case "$1" in
    start)
        echo -n "Avvio NCam "
       /usr/local/bin/ncam.x86_64 >> /var/log/ncam.log &
        # Remember status and be verbose
        ;;
    stop)
        echo -n "Chiusura di NCam "
       killall -9 ncam.x86_64
        # Remember status and be verbose
        ;;
    restart)
        echo -n "Riavvio di NCam "
        $0 stop
        $0 start

        # Remember status and be quiet
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
' >> /etc/init.d/ncam; chmod 755 /etc/init.d/ncam; echo "%`logname` ALL=NOPASSWD: /etc/init.d/ncam" >> /etc/sudoers; 
cd $SRC; mkdir -p ncam; cd ncam; cp -r /home/`logname`/sifinstallrepo/ncam.tar.gz /$SRC/ncam; tar -zxvf ncam.tar.gz; rm -rf ncam.tar.gz;
cp -r * /var/tuxbox/config/;
fi
cp -r /home/`logname`/sifinstallrepo/ncam64.tar.gz /usr/local/bin/; cd /usr/local/bin; tar -zxvf ncam64.tar.gz; rm -rf ncam64.tar.gz;
chmod 777 ncam.x86_64;

rm -rf /home/`logname`/Scrivania/NCam.desktop; rm -rf /usr/share/applications/NCam.desktop;
touch /home/`logname`/Scrivania/NCam.desktop; echo "[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Application
Name=NCam
Description=avvio di NCam
Icon=/usr/local/src/icone/ncam.png
Exec=/usr/local/bin/start-ncam.sh
" >> /home/`logname`/Scrivania/NCam.desktop; sudo chmod 777 /home/`logname`/Scrivania/NCam.desktop; cp /home/`logname`/Scrivania/NCam.desktop /usr/share/applications/NCam.desktop;
rm -rf /usr/local/bin/start-ncam.sh; touch /usr/local/bin/start-ncam.sh; echo '#!/bin/sh 
sleep 10
sudo /etc/init.d/ncam start > /dev/null 2>&1
' >> /usr/local/bin/start-ncam.sh; chmod a+x /usr/local/bin/start-ncam.sh;

rm -rf /home/`logname`/Scrivania/Killncam.desktop; rm -rf /usr/share/applications/Killncam.desktop;
touch /home/`logname`/Scrivania/Killncam.desktop; 
chmod 777 /home/`logname`/Scrivania/Killncam.desktop;
echo "[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Application
Name=Killncam
Description=Killa NCam
Icon=/usr/local/src/icone/killncam.png
Exec=/usr/local/bin/Killncam.sh
" >> /home/`logname`/Scrivania/Killncam.desktop; sudo chmod 777 /home/`logname`/Scrivania/Killncam.desktop; cp /home/`logname`/Scrivania/Killncam.desktop /usr/share/applications/Killncam.desktop;
rm -rf /usr/local/bin/Killncam.sh;
touch /usr/local/bin/Killncam.sh
echo '#!/bin/sh

sudo /etc/init.d/ncam stop > /dev/null 2>&1
' >> /usr/local/bin/Killncam.sh; chmod a+x /usr/local/bin/Killncam.sh;

    echo "                    Premere il tasto [Invio] per continuare. . .               "; read enterKey;;

#############################################################################################################################  
#############################################################################################################################
###                                                                                                                       ###
##                                                                                                                         ##
                                                                                                                     

                                          ##################################################
                                          #                   CCcam                         #
                                          ##################################################
                                          
d)                                                                                                                         

cd /var; mkdir -p etc;
if [ -f /var/etc/CCcam.check ];
  then  echo "CCcam_config $Remind3"
else
echo "CCcam ALL=(ALL) ALL" >> /etc/sudoers; 
cd $SRC; mkdir -p CCcam; cd CCcam; cp -r /home/`logname`/sifinstallrepo/CCcam.tar.gz /$SRC/CCcam; 
cd /$SRC/CCcam; tar -zxvf CCcam.tar.gz; rm -rf CCcam.tar.gz;
cp -r * /var/etc/; cd /var/etc/; chmod 755 *;
fi

cd /var; mkdir -p bin; cd /var/bin;
if [ -f /var/bin/ca.c ];
  then  echo "CCcam $Remind3"
else
cp -r /home/`logname`/sifinstallrepo/vdr-plugin-sc/contrib/cccam_ca.c /var/bin/ca.c;
cp -r /home/`logname`/sifinstallrepo/CCcam64.tar.gz /var/bin/; 
cd /var/bin; tar -zxvf CCcam64.tar.gz; rm -rf CCcam64.tar.gz; chmod 755 CCcam.x86_64;
fi

          # creazione icona avvio #
rm -rf /home/`logname`/Scrivania/CCcam.desktop; rm -rf /usr/share/applications/CCcam.desktop;
touch /home/`logname`/Scrivania/CCcam.desktop; echo "[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Application
Name=CCcam
Description=avvio di CCcam
Icon=/usr/local/src/icone/ccam.png
Exec=/var/bin/run.sh
" >> /home/`logname`/Scrivania/CCcam.desktop; sudo chmod 777 /home/`logname`/Scrivania/CCcam.desktop; cp -r /home/`logname`/Scrivania/CCcam.desktop /usr/share/applications/CCcam.desktop;

          # creazione icona chiusura #
rm -rf /home/`logname`/Scrivania/KillCCcam.desktop; rm -rf /usr/share/applications/KillCCcam.desktop;
touch /home/`logname`/Scrivania/KillCCcam.desktop; 
echo "[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Application
Name=Killccam
Description=Killa CCcam
Icon=/usr/local/src/icone/killccam.png
Exec=/usr/local/bin/KillCCcam.sh
" >> /home/`logname`/Scrivania/KillCCcam.desktop; sudo chmod 777 /home/`logname`/Scrivania/KillCCcam.desktop; cp -r /home/`logname`/Scrivania/KillCCcam.desktop /usr/share/applications/KillCCcam.desktop;

          # creazione comando avvio #
rm -rf /var/bin/run.sh; 
touch /var/bin/run.sh; 
echo "
#!/bin/sh

cd /var/bin
sudo gcc -march=athlon64 -mmmx -fomit-frame-pointer -fexpensive-optimizations -funroll-loops -fPIC -shared -o ca.so ca.c -ldl
LD_PRELOAD=./ca.so ; export LD_PRELOAD
sleep 2;
./CCcam.x86_64 -dv &
" >> /var/bin/run.sh; chmod 755 /var/bin/run.sh;

          # creazione comando chiusura #
rm -rf /usr/local/bin/KillCCcam.sh;
touch /usr/local/bin/KillCCcam.sh
echo '#!/bin/sh

sudo /etc/init.d/CCcam stop > /dev/null 2>&1
' >> /usr/local/bin/KillCCcam.sh; chmod 755 /usr/local/bin/KillCCcam.sh;

          # creazione comando CCcam nel etc/init.dinit.d  #
rm -r /etc/init.d/CCcam; touch /etc/init.d/CCcam; 
echo '
#!/bin/sh
#
# To be copied to: /etc/init.d
# And type:
### BEGIN INIT INFO
# Provides:          CCcam
# Required-Start:   
# Required-Stop:     
# Default-Start:     0 1 2 3 4 5 6
# Default-Stop:     
# Description:       Start, Stop or Restart CCcam
### END INIT INFO

# Shell functions sourced from /etc/rc.status:
set -e

# Reset status of this service
# rc_reset
#
echo "CCcam init.d script using: $1" >> /var/log/CCcam.log &
case "$1" in
    start)
        echo -n "Avvio CCcam "
        /var/bin/run.sh >> /var/log/CCcam.log &
        # Remember status and be verbose
        ;;
    stop)
        echo -n "Chiusura di CCcam "
        killall -9 CCcam.x86_64
        # Remember status and be verbose
        ;;
    restart)
        echo -n "Riavvio di CCcam "
        $0 stop
        $0 start

        # Remember status and be quiet
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
' >> /etc/init.d/CCcam; chmod 755 /etc/init.d/CCcam;


    echo "                    Premere il tasto [Invio] per continuare. . .               "; read enterKey;;

#############################################################################################################################  
#############################################################################################################################
###                                                                                                                       ###
##                                                                                                                         ##

 
z)   exit 0;;

#############################################################################################################################  
#############################################################################################################################
###                                                                                                                       ###
##                                                                                                                         ##

*) ;;
esac
done
